---
title: "Simple document"
output: github_document
---

```{r}
library(tidyverse)
```

Let's import the `FAS_litters.csv` using a relative path. 

```{r, eval = FALSE}
litters_df = 
  read_csv("data/FAS_litters.csv")

litters_df = 
  janitor::clean_names(litters_df)
```

Import the same dataset using an absolute path. (???)

Let's import the `FAS_pups.csv` using a relative path. 

```{r}
pups_df = 
  read_csv("data/FAS_pups.csv")

pups_df = 
  janitor::clean_names(pups_df)

pups_df
```

Let's import the `FAS_pups.csv` using an absolute path. (???)


##Look at data

```{r}
litters_df

head(litters_df)

tail(litters_df)
```

You can use `view` 

```{r, eval = FALSE}
view(litters_df)
```

Look at a data summary

```{r}
str(litters_df)

skimr::skim(litters_df)
```

## Options in `read_*`

```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    skip = 10, col_names = FALSE)
```

Look at NA values. 


```{r}
litters_df = 
  read_csv(
    "data/FAS_litters.csv",
    na = c("NA", 19, "."))
  )
```

Column types (???)

```{r}
litters_df = 
    read_csv(
      "data/FAS_litters.csv",
      col_types = 
        cols(
          `GD0 Weight` = col_character()
        ))

```

























